products_list = [
    {"title": "tiptop", "price": 35.60, "categories": ["0 a 3 meses", "roupas"]},
    {
        "title": "carrinho de bebê novinho",
        "price": 650.00,
        "categories": [
            "carrinhos",
            "0 a 3 meses",
            "4 a 6 meses",
            "7 a 9 meses",
            "10 meses a 1 ano",
            "2 anos",
            "3 a 5 anos",
        ],
    },
    {
        "title": "body tamanho p",
        "price": 29.90,
        "categories": ["0 a 3 meses", "roupas"],
    },
    {
        "title": "carrinho de bebê",
        "price": 569.00,
        "categories": [
            "carrinhos",
            "0 a 3 meses",
            "4 a 6 meses",
            "7 a 9 meses",
            "10 meses a 1 ano",
            "2 anos",
            "3 a 5 anos",
        ],
    },
    {
        "title": "poltrona de amamentação reclinável",
        "price": 759.00,
        "categories": ["lactação", "quarto do bebê"],
    },
    {
        "title": "babá eletrônica",
        "price": 250.00,
        "categories": [
            "segurança para bebê",
            "0 a 3 meses",
            "4 a 6 meses",
            "7 a 9 meses",
            "10 meses a 1 ano",
            "2 anos",
            "3 a 5 anos",
        ],
    },
    {
        "title": "berço",
        "price": 560.00,
        "categories": [
            "quarto do bebê",
            "0 a 3 meses",
            "4 a 6 meses",
            "7 a 9 meses",
            "10 meses a 1 ano",
            "2 anos",
            "3 a 5 anos",
        ],
    },
    {"title": "cobertorzinho", "price": 45.00, "categories": []},
    {"title": "Nanina", "price": 15.00, "categories": ["brinquedos"]},
    {"title": "body tamanho M", "price": 36.00, "categories": ["roupas"]},
    {
        "title": "Tênis tam 16",
        "price": 36.00,
        "categories": ["roupas", "0 a 3 meses"],
    },
    {
        "title": "jardineira",
        "price": 49.90,
        "categories": ["roupas", "4 a 6 meses"],
    },
    {
        "title": "colchão para carrinho de bebê",
        "price": 20.00,
        "categories": ["quarto do bebê"],
    },
    {
        "title": "bebê-conforto",
        "price": 350.00,
        "categories": [
            "segurança para bebê",
            "0 a 3 meses",
            "4 a 6 meses",
            "7 a 9 meses",
            "10 meses a 1 ano",
            "2 anos",
        ],
    },
]
