"""change cpf type

Revision ID: 1207917fdd0c
Revises: 263afee0f4f8
Create Date: 2022-04-26 22:23:04.814211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1207917fdd0c"
down_revision = "263afee0f4f8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "parents",
        "cpf",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "parents",
        "cpf",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
