"""create table cities in database

Revision ID: 130765d3bc5c
Revises: 13a375290b8a
Create Date: 2022-04-29 13:11:45.691326

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry


# revision identifiers, used by Alembic.
revision = '130765d3bc5c'
down_revision = '13a375290b8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_model',
    sa.Column('point_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo_ibge', sa.Integer(), nullable=True),
    sa.Column('nome_municipio', sa.String(), nullable=True),
    sa.Column('capital', sa.Boolean(), nullable=True),
    sa.Column('codigo_uf', sa.Integer(), nullable=True),
    sa.Column('uf', sa.String(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT'), nullable=True),
    sa.PrimaryKeyConstraint('point_id')
    )
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('city_model')
    # ### end Alembic commands ###
