"""Conserto - answer

Revision ID: 13a375290b8a
Revises: 006b1f759b6b
Create Date: 2022-04-27 16:34:06.258598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "13a375290b8a"
down_revision = "006b1f759b6b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("answers_parent_id_key", "answers", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("answers_parent_id_key", "answers", ["parent_id"])
    # ### end Alembic commands ###
