"""change columns in tables

Revision ID: 263afee0f4f8
Revises: 4aca4bcc4328
Create Date: 2022-04-26 22:16:22.662524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "263afee0f4f8"
down_revision = "4aca4bcc4328"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "answers",
        "parent_id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.drop_constraint("answers_parent_id_fkey", "answers", type_="foreignkey")
    op.create_foreign_key(None, "answers", "parents", ["parent_id"], ["id"])
    op.drop_constraint("products_parent_id_fkey", "products", type_="foreignkey")
    op.create_foreign_key(None, "products", "parents", ["parent_id"], ["id"])
    op.alter_column(
        "questions",
        "question",
        existing_type=sa.VARCHAR(length=2200),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.drop_constraint("questions_parent_id_fkey", "questions", type_="foreignkey")
    op.create_foreign_key(None, "questions", "parents", ["parent_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "questions", type_="foreignkey")
    op.create_foreign_key(
        "questions_parent_id_fkey", "questions", "parents", ["parent_id"], ["cpf"]
    )
    op.alter_column(
        "questions",
        "question",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=2200),
        existing_nullable=False,
    )
    op.drop_constraint(None, "products", type_="foreignkey")
    op.create_foreign_key(
        "products_parent_id_fkey", "products", "parents", ["parent_id"], ["cpf"]
    )
    op.drop_constraint(None, "answers", type_="foreignkey")
    op.create_foreign_key(
        "answers_parent_id_fkey", "answers", "parents", ["parent_id"], ["cpf"]
    )
    op.alter_column(
        "answers",
        "parent_id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
