"""add columns fk parents_id and msg_read in table messages

Revision ID: 45165ec0bc8f
Revises: a527eb411a08
Create Date: 2022-05-04 20:47:55.702891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45165ec0bc8f'
down_revision = 'a527eb411a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('messages', sa.Column('msg_read', sa.Boolean(), nullable=False))
    op.add_column('messages', sa.Column('parent_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'messages', 'parents', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'parent_id')
    op.drop_column('messages', 'msg_read')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
