"""change columns username, email and phone to unique

Revision ID: 4772d8e2a3e3
Revises: 1207917fdd0c
Create Date: 2022-04-27 11:00:42.006497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4772d8e2a3e3"
down_revision = "1207917fdd0c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "parents", ["username"])
    op.create_unique_constraint(None, "parents", ["email"])
    op.create_unique_constraint(None, "parents", ["phone"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "parents", type_="unique")
    op.drop_constraint(None, "parents", type_="unique")
    op.drop_constraint(None, "parents", type_="unique")
    # ### end Alembic commands ###
