"""Create Table questions

Revision ID: 54f9fbd967eb
Revises: 0c00d8bb1f3a
Create Date: 2022-04-26 11:33:42.783922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "54f9fbd967eb"
down_revision = "0c00d8bb1f3a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question", sa.VARCHAR(length=2200), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["parents.cpf"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("questions")
    # ### end Alembic commands ###
