"""Adicionando table answer

Revision ID: 60d097e29c45
Revises: 54f9fbd967eb
Create Date: 2022-04-26 15:20:19.272523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "60d097e29c45"
down_revision = "54f9fbd967eb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "answers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("answer", sa.String(length=150), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["parents.cpf"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("parent_id"),
        sa.UniqueConstraint("question_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("answers")
    # ### end Alembic commands ###
