"""add_image_profile_and_products

Revision ID: 6999960bf05e
Revises: 12a425886820
Create Date: 2022-06-13 16:40:55.284709

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6999960bf05e"
down_revision = "12a425886820"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("parents", sa.Column("image", sa.String(), nullable=True))
    op.add_column("products", sa.Column("image1", sa.String(), nullable=True))
    op.add_column("products", sa.Column("image2", sa.String(), nullable=True))
    op.add_column("products", sa.Column("image3", sa.String(), nullable=True))
    op.add_column("products", sa.Column("image4", sa.String(), nullable=True))
    op.drop_column("products", "image")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("image", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("products", "image4")
    op.drop_column("products", "image3")
    op.drop_column("products", "image2")
    op.drop_column("products", "image1")
    op.drop_column("parents", "image")
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "(srid > 0) AND (srid <= 998999)", name="spatial_ref_sys_srid_check"
        ),
        sa.PrimaryKeyConstraint("srid", name="spatial_ref_sys_pkey"),
    )
    # ### end Alembic commands ###
