"""add delete on cascade

Revision ID: 6c32496ce0cd
Revises: 13a375290b8a
Create Date: 2022-04-28 20:14:10.971449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6c32496ce0cd"
down_revision = "13a375290b8a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("answers_parent_id_fkey", "answers", type_="foreignkey")
    op.drop_constraint("answers_question_id_fkey", "answers", type_="foreignkey")
    op.create_foreign_key(
        None, "answers", "parents", ["parent_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "answers", "questions", ["question_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("products_parent_id_fkey", "products", type_="foreignkey")
    op.create_foreign_key(
        None, "products", "parents", ["parent_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("questions_parent_id_fkey", "questions", type_="foreignkey")
    op.drop_constraint("questions_product_id_fkey", "questions", type_="foreignkey")
    op.create_foreign_key(
        None, "questions", "parents", ["parent_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "questions", "products", ["product_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "questions", type_="foreignkey")
    op.drop_constraint(None, "questions", type_="foreignkey")
    op.create_foreign_key(
        "questions_product_id_fkey", "questions", "products", ["product_id"], ["id"]
    )
    op.create_foreign_key(
        "questions_parent_id_fkey", "questions", "parents", ["parent_id"], ["id"]
    )
    op.drop_constraint(None, "products", type_="foreignkey")
    op.create_foreign_key(
        "products_parent_id_fkey", "products", "parents", ["parent_id"], ["id"]
    )
    op.drop_constraint(None, "answers", type_="foreignkey")
    op.drop_constraint(None, "answers", type_="foreignkey")
    op.create_foreign_key(
        "answers_question_id_fkey", "answers", "questions", ["question_id"], ["id"]
    )
    op.create_foreign_key(
        "answers_parent_id_fkey", "answers", "parents", ["parent_id"], ["id"]
    )
    # ### end Alembic commands ###
