"""fix password to password_hash

Revision ID: 9f44045110e3
Revises: 54f9fbd967eb
Create Date: 2022-04-26 15:46:23.130031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f44045110e3'
down_revision = '54f9fbd967eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parents', sa.Column('password_hash', sa.String(), nullable=False))
    op.drop_column('parents', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parents', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('parents', 'password_hash')
    # ### end Alembic commands ###
