"""add in table parent columns municipio and estado

Revision ID: aada6e74ebdc
Revises: 1da534bf273c
Create Date: 2022-04-30 22:52:05.249255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aada6e74ebdc'
down_revision = '1da534bf273c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    # op.drop_table('zcta')
    op.drop_index('idx_city_model_geom', table_name='city_model')
    op.add_column('parents', sa.Column('nome_municipio', sa.String(), nullable=False))
    op.add_column('parents', sa.Column('estado', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parents', 'estado')
    op.drop_column('parents', 'nome_municipio')
    op.create_index('idx_city_model_geom', 'city_model', ['geom'], unique=False)
    op.create_table('zcta',
    sa.Column('zip', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326), autoincrement=False, nullable=True)
    )
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
