"""add dates question/answer

Revision ID: b53474150de5
Revises: 9e5d33ff6cfa
Create Date: 2022-05-04 16:26:34.947693

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b53474150de5"
down_revision = "9e5d33ff6cfa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column("answers", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("answers", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column("questions", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("questions", sa.Column("updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "updated_at")
    op.drop_column("questions", "created_at")
    op.drop_column("answers", "updated_at")
    op.drop_column("answers", "created_at")
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "(srid > 0) AND (srid <= 998999)", name="spatial_ref_sys_srid_check"
        ),
        sa.PrimaryKeyConstraint("srid", name="spatial_ref_sys_pkey"),
    )
    # ### end Alembic commands ###
