"""add_image_key_profile_and_products

Revision ID: bbbd289e970c
Revises: 6999960bf05e
Create Date: 2022-06-17 11:35:49.733330

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bbbd289e970c"
down_revision = "6999960bf05e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column("parents", sa.Column("image_key", sa.String(), nullable=True))
    op.add_column("products", sa.Column("image1_key", sa.String(), nullable=True))
    op.add_column("products", sa.Column("image2_key", sa.String(), nullable=True))
    op.add_column("products", sa.Column("image3_key", sa.String(), nullable=True))
    op.add_column("products", sa.Column("image4_key", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "image4_key")
    op.drop_column("products", "image3_key")
    op.drop_column("products", "image2_key")
    op.drop_column("products", "image1_key")
    op.drop_column("parents", "image_key")
    op.create_table(
        "spatial_ref_sys",
        sa.Column("srid", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "auth_name", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("auth_srid", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "srtext", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.Column(
            "proj4text", sa.VARCHAR(length=2048), autoincrement=False, nullable=True
        ),
        sa.CheckConstraint(
            "(srid > 0) AND (srid <= 998999)", name="spatial_ref_sys_srid_check"
        ),
        sa.PrimaryKeyConstraint("srid", name="spatial_ref_sys_pkey"),
    )
    # ### end Alembic commands ###
