"""fix password to password_hash

Revision ID: cfd70f846b72
Revises: e5fe1d59c376
Create Date: 2022-04-26 17:45:27.482420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cfd70f846b72"
down_revision = "e5fe1d59c376"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("parents", sa.Column("password_hash", sa.String(), nullable=False))
    op.drop_column("parents", "password")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "parents",
        sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("parents", "password_hash")
    # ### end Alembic commands ###
