"""add col name table category

Revision ID: e5fe1d59c376
Revises: 60d097e29c45
Create Date: 2022-04-26 17:26:05.508853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5fe1d59c376'
down_revision = '60d097e29c45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'name')
    # ### end Alembic commands ###
