"""create table cities

Revision ID: f294c3951812
Revises: 6c32496ce0cd
Create Date: 2022-05-02 16:34:02.715898

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry


# revision identifiers, used by Alembic.
revision = 'f294c3951812'
down_revision = '6c32496ce0cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('point_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code_ibge', sa.Integer(), nullable=True),
    sa.Column('name_county', sa.String(), nullable=True),
    sa.Column('capital', sa.Boolean(), nullable=True),
    sa.Column('code_uf', sa.Integer(), nullable=True),
    sa.Column('uf', sa.String(), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('geom', Geometry(geometry_type='POINT'), nullable=True),
    sa.PrimaryKeyConstraint('point_id')
    )
    # op.drop_table('spatial_ref_sys')
    op.create_unique_constraint(None, 'categories', ['name'])
    op.add_column('parents', sa.Column('city_point_id', sa.Integer(), nullable=False))
    op.drop_constraint('parents_phone_key', 'parents', type_='unique')
    op.create_foreign_key(None, 'parents', 'cities', ['city_point_id'], ['point_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parents', type_='foreignkey')
    op.create_unique_constraint('parents_phone_key', 'parents', ['phone'])
    op.drop_column('parents', 'city_point_id')
    op.drop_constraint(None, 'categories', type_='unique')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('cities')
    # ### end Alembic commands ###
